version: '3'
services:
  config:
   container_name: config
   image: nick147/config:latest
   restart: always
   ports:
   - 8091:8091
  eureka:
   container_name: eureka
   image: nick147/eureka:latest
   restart: always
   ports:
   - 8082:8082
  tbu:
   container_name: tbu
   image: nick147/tbu:latest
   restart: always
   ports:
   - 8010:8010
#  data:
#   container_name: data
#   image: nick147/data:latest
#   restart: always
#   ports:
#   - 8085:8085
#   volumes:
#   - my-mongo:/var/lib/mongo
  generator:
   container_name: generator
   image: nick147/generator:latest
   restart: always
   ports:
   - 8078:8078



