version: '3'
services:
  config:
   container_name: config
   image: nick147/config:latest
   restart: always
   ports:
   - 8091:8091
  eureka:
   container_name: eureka
   image: nick147/eureka:latest
   restart: always
   ports:
   - 8082:8082




